### ISSUE TITLE
Minor jitter after every scroll due to Emacs' self-correction

### ISSUE THREAD

**Issue by ianpan870102** [io12/good-scroll.el#12]
This is hands-down the best smooth scrolling implementation -- it's almost perfect! There's just one minor complaint:

When the user is done with a smooth scroll, sometimes it stops at half the line height, meaning that the visible top line and bottom line of the buffer can appear to be cut off by half. Which is absolutely fine, except that when the user starts typing or starts moving around with the arrow keys, Emacs will correct the buffer display and adjust such that the top line and bottom line are wholly visible. This results in a jitter every time good-scroll stops at the fraction of a line height and the user starts typing with the keyboard.

Please let me know if I explained it all right. It's kinda hard to put into words.

Nevertheless, this is really a great implementation, I wish more people discover it.

**Comment by io12** [comment]
Yeah I know what you're talking about. One option is to round the scroll destination so a scroll always stops on a line edge, but for lines with images you wouldn't be able to scroll halfway through an image. I haven't actually looked into why Emacs resets the vscroll when you start typing, so I could look into ways to disable that. Thanks!

**Comment by ianpan870102** [comment]
> One option is to round the scroll destination so a scroll always stops on a line edge

Thanks for the prompt reply! Personally, I don't have images to scroll with. Could you perhaps point me to how I can round the scroll destination (to stop at line edge) myself? My Emacs Lisp skills are sadly not as good as I'd like them to be.

**Comment by ianpan870102** [comment]
I was thinking perhaps the user could set `good-scroll-step` to a multiplier of "font-height + line-spacing", so no matter how many turns the mouse wheel rotates, the scrolling will always use "font-height + line-spacing" as a base unit, hence always stopping at a line edge. However, I tried the following snippet and it didn't work:

```emacs-lisp
(setq ian/normal-fontsize 110)
(setq-default line-spacing 2)
(setq good-scroll-step (* (+ (/ ian/normal-fontsize 10) line-spacing) 14))
```

**Comment by io12** [comment]
The `line-pixel-height` function should get the height of the current line, so if all your lines are the same height then setting `good-scroll-step` to that should probably work. I also looked into the reason why this happens at all and it looks like the `line-move` function (which gets called when you move the point) resets vscroll. I'm working on a feature to avoid this in the `avoid-vscroll-reset` branch. It reverts back to the old behavior when the point's at the top of the window though, because otherwise causes performance issues for some reason.

**Comment by io12** [comment]
Okay I merged the branch. This should be fixed now with https://github.com/io12/good-scroll.el/commit/fa0bd6be9ba97de81a07631c8768b8cec39f47b2. It also adds a toggleable `good-scroll-avoid-vscroll-reset` for people who want to keep the old behavior.

**Comment by ianpan870102** [comment]
Thanks a ton! The latest commit is working like a charm.
