### ISSUE TITLE
scroll action during page-up and page-down

### ISSUE THREAD

**Issue by rhoit** [io12/good-scroll.el#18]
can `good-scroll.el` enable for **page-up** and **page-down** action!

**Comment by io12** [comment]
You can bind `<PageUp>` and `<PageDown>` to `good-scroll-up` and `good-scroll-down`, but they won't go down a full screen. I want to make this more configurable at one point though.

**Comment by io12** [comment]
I added this just now in https://github.com/io12/good-scroll.el/commit/5f242d46df28a8399d530fe42006568e58afb61f. Setup info is in the README https://github.com/io12/good-scroll.el#key-bindings.
