### ISSUE TITLE
using wheel with good-scroll and linum-mode the line numbers sometimes disappear

### ISSUE THREAD

**Issue by Allinaent** [io12/good-scroll.el#25]
Using wheel with good-scroll and linum-mode the line numbers sometimes disappear. But click left mouse, the line numbers will appear.

**Comment by io12** [comment]
Thanks for this bug report! I don't use `linum-mode` so I didn't notice this. I have a work-in-progress fix in the `run-wsf-after-set-window-start` branch, but it seems to have slow performance with `linum-mode`.

**Comment by io12** [comment]
It looks like `display-line-numbers-mode` is newer than `linum-mode` and faster, and works fine with good-scroll. I don't think it's worth fixing the `linum-mode` disappearance bug, since the fix worsens performance and may have unintended issues for other packages. Thanks anyway though!

**Comment by io12** [comment]
I'm going to delete the `run-wsf-after-set-window-start` branch, but the `linum-mode` fix was calling `(run-window-scroll-functions)` after all `set-window-start` calls in `good-scroll--render`.

```diff
diff --git a/good-scroll.el b/good-scroll.el
index b7c250c..723989f 100644
--- a/good-scroll.el
+++ b/good-scroll.el
@@ -566,6 +566,7 @@ line."
                             (vertical-motion 1)
                             (point))
                       t)
+    (run-window-scroll-functions)
     (good-scroll--log "good-scroll--go-to-up-full after"
                       (window-start)
                       good-scroll--cached-point-top
@@ -627,6 +628,7 @@ Return the next target scroll position. Assume POS > VSCROLL."
                             (vertical-motion -1)
                             (point))
                       t)
+    (run-window-scroll-functions)
     (good-scroll--log "good-scroll--go-to-down-full after"
                       (good-scroll--point-top))
     (+ pos vscroll
-- 
2.34.1
```
