### ISSUE TITLE
line number disappear when scroll up or down

### ISSUE THREAD

**Issue by pipiTan** [io12/good-scroll.el#27]
Thanks a lot for this amazing plugin, i really enjoy it.
But line number will disappear when scroll up or down. Mouse click or other action can make it normal.
Though it is not even a bug, it just make me feel a bit uncomfortable. how can i fix it?

**Comment by io12** [comment]
If this is the same issue as https://github.com/io12/good-scroll.el/issues/25, you can fix it by switching from `linum-mode` to `display-line-numbers-mode`. Let me know if that helps or if you're using something other than `linum-mode`.

**Comment by io12** [comment]
I'm going to close this issue now, but feel free to open it again if the above comment doesn't help.
