### ISSUE TITLE
Interruption of scrolling

### ISSUE THREAD

**Issue by black7375** [io12/good-scroll.el#4]
Much faster than `pixel-scroll-mode`!!
This alone is really good.

Occasional breaks appear when scrolling.
It seems to appear more when scrolling upwards.
![output-2020-12-21-00:10:38](https://user-images.githubusercontent.com/25581533/102716747-b52ca000-42d5-11eb-9deb-99733b51b839.gif)

The options related to scrolling were not modified and used as defaults.
`mouse-wheel-scroll-amount`, `mouse-wheel-progressive-speed`, `scroll-step`...

**Comment by black7375** [comment]
Notes related to adjusting options.

**Better**
`mouse-wheel-progressive-speed` is definitely too much.
```emacs lisp
(setq mouse-wheel-progressive-speed nil) 
```

**Conflict?**
[Reddit comment](https://www.reddit.com/r/emacs/comments/kgr3uz/goodscrollel_attempt_at_good_pixelbased_smooth/gghhkdf?utm_source=share&utm_medium=web2x&context=3)'s rebounds
```emacs lisp
(scroll-margin  3) ;; or another integer
```

**Comment by black7375** [comment]
I tried a few things and got a satisfactory result.

Here is my config
```emacs lisp
(use-feature emacs
  :disabled
  :custom
  ;; https://www.masteringemacs.org/article/improving-performance-emacs-display-engine
  ;; https://www.gnu.org/software/emacs/manual/html_node/emacs/Auto-Scrolling.html
  ;; https://www.reddit.com/r/emacs/comments/8sw3r0/finally_scrolling_over_large_images_with_pixel/
  ;; https://www.reddit.com/r/emacs/comments/9rwb4h/why_does_fast_scrolling_freeze_the_screen/
  ;; https://emacs.stackexchange.com/questions/10354/smooth-mouse-scroll-for-inline-images
  ;; https://emacs.stackexchange.com/questions/28736/emacs-pointcursor-movement-lag
  ;; https://www.emacswiki.org/emacs/InertialScrolling
  ;; https://www.emacswiki.org/emacs/SmoothScrolling
  ;; https://github.com/ahungry/fast-scroll
  (redisplay-dont-pause            t) ;; Fully redraw the display before it processes queued input events.
  (next-screen-context-lines       2) ;; Number of lines of continuity to retain when scrolling by full screens
  (scroll-conservatively       10000) ;; only 'jump' when moving this far off the screen
  (scroll-step                     1) ;; Keyboard scroll one line at a time
  (mouse-wheel-progressive-speed nil) ;; Don't accelerate scrolling
  (mouse-wheel-follow-mouse        t) ;; Scroll window under mouse
  (fast-but-imprecise-scrolling    t) ;; No (less) lag while scrolling lots.
  (auto-window-vscroll           nil) ;; Cursor move faster
  )

;; Inertial Scrolling - Better than progressive-speed
(use-package inertial-scroll
  :custom
  (inertias-friction 110)
  :bind
  (("<mouse-4>"     . inertias-down-wheel) ;; Replace mwheel-scroll
   ("<mouse-5>"     . inertias-up-wheel  ) ;; Replace mwheel-scroll
   ("<wheel-up>"    . inertias-down-wheel)
   ("<wheel-down>"  . inertias-up-wheel  )))

;; Pixel-scroll alternative
(use-package good-scroll
  :straight (good-scroll :type git :host github :repo "io12/good-scroll.el")
  :hook (after-init . good-scroll-mode))
```

**Comment by io12** [comment]
Thanks! Looks like there are some conflicts with some of the default scroll options (`mouse-wheel-progressive-speed` and `mouse-wheel-scroll-amount`). I had these set to custom values, so I didn't know they were a problem. I pushed https://github.com/io12/good-scroll.el/commit/4c685e05b9745d914c8553dc6b8fd06babd56528, which ignores `mouse-wheel-scroll-amount` and partially fixes `mouse-wheel-progressive-speed`.

Honestly, it might be worth it for `good-scroll` to bypass `mwheel.el` entirely and manually bind the scroll buttons.

**Comment by io12** [comment]
New issue for removing `mwheel.el` dependency: https://github.com/io12/good-scroll.el/issues/5
